// <auto-generated />
using System;
using BankTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankTest.Migrations
{
    [DbContext(typeof(BankTestContext))]
    [Migration("20220620062416_addeed EntityBase")]
    partial class addeedEntityBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankTest.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PersonalPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Addresses = "Some Adress 0",
                            DateofBirth = new DateTime(1971, 6, 20, 8, 24, 16, 505, DateTimeKind.Local).AddTicks(962),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "57458843",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 2,
                            Addresses = "Some Adress 1",
                            DateofBirth = new DateTime(2005, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(6549),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "60809378",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 3,
                            Addresses = "Some Adress 2",
                            DateofBirth = new DateTime(1945, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7051),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "73603554",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 4,
                            Addresses = "Some Adress 3",
                            DateofBirth = new DateTime(2007, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7096),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "48153440",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 5,
                            Addresses = "Some Adress 4",
                            DateofBirth = new DateTime(1956, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7122),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "96883936",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 6,
                            Addresses = "Some Adress 5",
                            DateofBirth = new DateTime(1992, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7149),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "58535167",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 7,
                            Addresses = "Some Adress 6",
                            DateofBirth = new DateTime(1976, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7170),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "90329650",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 8,
                            Addresses = "Some Adress 7",
                            DateofBirth = new DateTime(2005, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7190),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "20758542",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 9,
                            Addresses = "Some Adress 8",
                            DateofBirth = new DateTime(1975, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7210),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "14173980",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 10,
                            Addresses = "Some Adress 9",
                            DateofBirth = new DateTime(2008, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7231),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "95865415",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 11,
                            Addresses = "Some Adress 10",
                            DateofBirth = new DateTime(2010, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7251),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "51359263",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 12,
                            Addresses = "Some Adress 11",
                            DateofBirth = new DateTime(1968, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7272),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "89290516",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 13,
                            Addresses = "Some Adress 12",
                            DateofBirth = new DateTime(1973, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7292),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "59516514",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 14,
                            Addresses = "Some Adress 13",
                            DateofBirth = new DateTime(2008, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7311),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "95418698",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 15,
                            Addresses = "Some Adress 14",
                            DateofBirth = new DateTime(1945, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7330),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "76030078",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 16,
                            Addresses = "Some Adress 15",
                            DateofBirth = new DateTime(1959, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7526),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "39923151",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 17,
                            Addresses = "Some Adress 16",
                            DateofBirth = new DateTime(1989, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7554),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "12624451",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 18,
                            Addresses = "Some Adress 17",
                            DateofBirth = new DateTime(2008, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7577),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "78756894",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 19,
                            Addresses = "Some Adress 18",
                            DateofBirth = new DateTime(1997, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7598),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "23427955",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 20,
                            Addresses = "Some Adress 19",
                            DateofBirth = new DateTime(1943, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7618),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "72263250",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 21,
                            Addresses = "Some Adress 20",
                            DateofBirth = new DateTime(2004, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7637),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "42543858",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 22,
                            Addresses = "Some Adress 21",
                            DateofBirth = new DateTime(1991, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7656),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "40249616",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 23,
                            Addresses = "Some Adress 22",
                            DateofBirth = new DateTime(1992, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7676),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "29664430",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 24,
                            Addresses = "Some Adress 23",
                            DateofBirth = new DateTime(1975, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7695),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "85014162",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 25,
                            Addresses = "Some Adress 24",
                            DateofBirth = new DateTime(1991, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7714),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "35509647",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 26,
                            Addresses = "Some Adress 25",
                            DateofBirth = new DateTime(1955, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7734),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "89370274",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 27,
                            Addresses = "Some Adress 26",
                            DateofBirth = new DateTime(2008, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7753),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "67723344",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 28,
                            Addresses = "Some Adress 27",
                            DateofBirth = new DateTime(1944, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7773),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "46918609",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 29,
                            Addresses = "Some Adress 28",
                            DateofBirth = new DateTime(1961, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7793),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "30627746",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 30,
                            Addresses = "Some Adress 29",
                            DateofBirth = new DateTime(2012, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7812),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "58045492",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 31,
                            Addresses = "Some Adress 30",
                            DateofBirth = new DateTime(2002, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7884),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "60033298",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 32,
                            Addresses = "Some Adress 31",
                            DateofBirth = new DateTime(1954, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7906),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "66951804",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 33,
                            Addresses = "Some Adress 32",
                            DateofBirth = new DateTime(1983, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7926),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "24779799",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 34,
                            Addresses = "Some Adress 33",
                            DateofBirth = new DateTime(1966, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7948),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "43422660",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 35,
                            Addresses = "Some Adress 34",
                            DateofBirth = new DateTime(2004, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(7998),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "73324967",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 36,
                            Addresses = "Some Adress 35",
                            DateofBirth = new DateTime(2007, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8018),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "14917481",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 37,
                            Addresses = "Some Adress 36",
                            DateofBirth = new DateTime(1993, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8038),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "19692824",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 38,
                            Addresses = "Some Adress 37",
                            DateofBirth = new DateTime(1977, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8057),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "84595192",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 39,
                            Addresses = "Some Adress 38",
                            DateofBirth = new DateTime(1989, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8077),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "41474135",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 40,
                            Addresses = "Some Adress 39",
                            DateofBirth = new DateTime(1973, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8096),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "98722102",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 41,
                            Addresses = "Some Adress 40",
                            DateofBirth = new DateTime(1968, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8115),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "53242922",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 42,
                            Addresses = "Some Adress 41",
                            DateofBirth = new DateTime(1981, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8135),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "76305280",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 43,
                            Addresses = "Some Adress 42",
                            DateofBirth = new DateTime(1958, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8154),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "74629412",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 44,
                            Addresses = "Some Adress 43",
                            DateofBirth = new DateTime(1991, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8173),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "39457789",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 45,
                            Addresses = "Some Adress 44",
                            DateofBirth = new DateTime(1955, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8192),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "31426369",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 46,
                            Addresses = "Some Adress 45",
                            DateofBirth = new DateTime(1958, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8263),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "70220895",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 47,
                            Addresses = "Some Adress 46",
                            DateofBirth = new DateTime(2006, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8283),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "63747766",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 48,
                            Addresses = "Some Adress 47",
                            DateofBirth = new DateTime(1956, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8303),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "79215377",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 49,
                            Addresses = "Some Adress 48",
                            DateofBirth = new DateTime(1958, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8322),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "21907875",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 50,
                            Addresses = "Some Adress 49",
                            DateofBirth = new DateTime(1969, 6, 20, 8, 24, 16, 510, DateTimeKind.Local).AddTicks(8341),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "83229788",
                            SecondName = "Doe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
