// <auto-generated />
using System;
using BankTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankTest.Migrations
{
    [DbContext(typeof(BankTestContext))]
    [Migration("20220603143524_x")]
    partial class x
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankTest.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Addresses = "Some Adress 0",
                            DateofBirth = new DateTime(1969, 6, 3, 16, 35, 24, 484, DateTimeKind.Local).AddTicks(5992),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "89455904",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 2,
                            Addresses = "Some Adress 1",
                            DateofBirth = new DateTime(1963, 6, 3, 16, 35, 24, 489, DateTimeKind.Local).AddTicks(9774),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "54040636",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 3,
                            Addresses = "Some Adress 2",
                            DateofBirth = new DateTime(1955, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(104),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "94468128",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 4,
                            Addresses = "Some Adress 3",
                            DateofBirth = new DateTime(1967, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(136),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "93474329",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 5,
                            Addresses = "Some Adress 4",
                            DateofBirth = new DateTime(1973, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(154),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "31647375",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 6,
                            Addresses = "Some Adress 5",
                            DateofBirth = new DateTime(1970, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(177),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "12195180",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 7,
                            Addresses = "Some Adress 6",
                            DateofBirth = new DateTime(1950, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(196),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "83556445",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 8,
                            Addresses = "Some Adress 7",
                            DateofBirth = new DateTime(2002, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(213),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "30040244",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 9,
                            Addresses = "Some Adress 8",
                            DateofBirth = new DateTime(1953, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(231),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "24977963",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 10,
                            Addresses = "Some Adress 9",
                            DateofBirth = new DateTime(1947, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(249),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "54812582",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 11,
                            Addresses = "Some Adress 10",
                            DateofBirth = new DateTime(1946, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(268),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "57046074",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 12,
                            Addresses = "Some Adress 11",
                            DateofBirth = new DateTime(1983, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(284),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "85315823",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 13,
                            Addresses = "Some Adress 12",
                            DateofBirth = new DateTime(1968, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(301),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "84097475",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 14,
                            Addresses = "Some Adress 13",
                            DateofBirth = new DateTime(1955, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(318),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "27633972",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 15,
                            Addresses = "Some Adress 14",
                            DateofBirth = new DateTime(1976, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(335),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "71228549",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 16,
                            Addresses = "Some Adress 15",
                            DateofBirth = new DateTime(1947, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(353),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "42317905",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 17,
                            Addresses = "Some Adress 16",
                            DateofBirth = new DateTime(1959, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(469),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "89624763",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 18,
                            Addresses = "Some Adress 17",
                            DateofBirth = new DateTime(1948, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(488),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "73845081",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 19,
                            Addresses = "Some Adress 18",
                            DateofBirth = new DateTime(1945, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(505),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "73828044",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 20,
                            Addresses = "Some Adress 19",
                            DateofBirth = new DateTime(1948, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(522),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "81430667",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 21,
                            Addresses = "Some Adress 20",
                            DateofBirth = new DateTime(1958, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(538),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "54591593",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 22,
                            Addresses = "Some Adress 21",
                            DateofBirth = new DateTime(1945, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(555),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "63718576",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 23,
                            Addresses = "Some Adress 22",
                            DateofBirth = new DateTime(1986, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(571),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "46897401",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 24,
                            Addresses = "Some Adress 23",
                            DateofBirth = new DateTime(1973, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(587),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "44373899",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 25,
                            Addresses = "Some Adress 24",
                            DateofBirth = new DateTime(1989, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(603),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "55532226",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 26,
                            Addresses = "Some Adress 25",
                            DateofBirth = new DateTime(1948, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(620),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "60374939",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 27,
                            Addresses = "Some Adress 26",
                            DateofBirth = new DateTime(1981, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(636),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "26307650",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 28,
                            Addresses = "Some Adress 27",
                            DateofBirth = new DateTime(1944, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(653),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "72888287",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 29,
                            Addresses = "Some Adress 28",
                            DateofBirth = new DateTime(1982, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(670),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "88870007",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 30,
                            Addresses = "Some Adress 29",
                            DateofBirth = new DateTime(1966, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(686),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "87524206",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 31,
                            Addresses = "Some Adress 30",
                            DateofBirth = new DateTime(1959, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(702),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "33731167",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 32,
                            Addresses = "Some Adress 31",
                            DateofBirth = new DateTime(1987, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(763),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "20507805",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 33,
                            Addresses = "Some Adress 32",
                            DateofBirth = new DateTime(1952, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(782),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "66173873",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 34,
                            Addresses = "Some Adress 33",
                            DateofBirth = new DateTime(1943, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(801),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "73603773",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 35,
                            Addresses = "Some Adress 34",
                            DateofBirth = new DateTime(1987, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(818),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "79799262",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 36,
                            Addresses = "Some Adress 35",
                            DateofBirth = new DateTime(1944, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(834),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "11592701",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 37,
                            Addresses = "Some Adress 36",
                            DateofBirth = new DateTime(1961, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(850),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "65043867",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 38,
                            Addresses = "Some Adress 37",
                            DateofBirth = new DateTime(1994, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(866),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "46830931",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 39,
                            Addresses = "Some Adress 38",
                            DateofBirth = new DateTime(1951, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(882),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "67736479",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 40,
                            Addresses = "Some Adress 39",
                            DateofBirth = new DateTime(1981, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(899),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "65456227",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 41,
                            Addresses = "Some Adress 40",
                            DateofBirth = new DateTime(1965, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(915),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "12389777",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 42,
                            Addresses = "Some Adress 41",
                            DateofBirth = new DateTime(1946, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(931),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "33408866",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 43,
                            Addresses = "Some Adress 42",
                            DateofBirth = new DateTime(1961, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(948),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "91560514",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 44,
                            Addresses = "Some Adress 43",
                            DateofBirth = new DateTime(1943, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(964),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "85481481",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 45,
                            Addresses = "Some Adress 44",
                            DateofBirth = new DateTime(1972, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(980),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "48599173",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 46,
                            Addresses = "Some Adress 45",
                            DateofBirth = new DateTime(1992, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(1052),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "82993274",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 47,
                            Addresses = "Some Adress 46",
                            DateofBirth = new DateTime(1964, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(1071),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "34580808",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 48,
                            Addresses = "Some Adress 47",
                            DateofBirth = new DateTime(1947, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(1087),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "53367935",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 49,
                            Addresses = "Some Adress 48",
                            DateofBirth = new DateTime(1997, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(1104),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "58002641",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 50,
                            Addresses = "Some Adress 49",
                            DateofBirth = new DateTime(1958, 6, 3, 16, 35, 24, 490, DateTimeKind.Local).AddTicks(1120),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "39610946",
                            SecondName = "Tapanez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
