// <auto-generated />
using System;
using BankTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankTest.Migrations
{
    [DbContext(typeof(BankTestContext))]
    [Migration("20220603101248_first migration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankTest.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Addresses = "Some Adress 0",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 201, DateTimeKind.Unspecified).AddTicks(7968),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "64438592",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 2,
                            Addresses = "Some Adress 1",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 606, DateTimeKind.Unspecified).AddTicks(8433),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "17850619",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 3,
                            Addresses = "Some Adress 2",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 822, DateTimeKind.Unspecified).AddTicks(6207),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "47162071",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 4,
                            Addresses = "Some Adress 3",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 313, DateTimeKind.Unspecified).AddTicks(4644),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "77440155",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 5,
                            Addresses = "Some Adress 4",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 578, DateTimeKind.Unspecified).AddTicks(9046),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "83567678",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 6,
                            Addresses = "Some Adress 5",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 183, DateTimeKind.Unspecified).AddTicks(2314),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "77548711",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 7,
                            Addresses = "Some Adress 6",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 557, DateTimeKind.Unspecified).AddTicks(5941),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "54877433",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 8,
                            Addresses = "Some Adress 7",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 551, DateTimeKind.Unspecified).AddTicks(6597),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "34442303",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 9,
                            Addresses = "Some Adress 8",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 669, DateTimeKind.Unspecified).AddTicks(7169),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "29160323",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 10,
                            Addresses = "Some Adress 9",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 927, DateTimeKind.Unspecified).AddTicks(6606),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "32247470",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 11,
                            Addresses = "Some Adress 10",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 601, DateTimeKind.Unspecified).AddTicks(254),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "34726564",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 12,
                            Addresses = "Some Adress 11",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 567, DateTimeKind.Unspecified).AddTicks(8563),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "24351959",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 13,
                            Addresses = "Some Adress 12",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 668, DateTimeKind.Unspecified).AddTicks(1892),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "48481252",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 14,
                            Addresses = "Some Adress 13",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 582, DateTimeKind.Unspecified).AddTicks(8460),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "73861815",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 15,
                            Addresses = "Some Adress 14",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 395, DateTimeKind.Unspecified).AddTicks(130),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "89208886",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 16,
                            Addresses = "Some Adress 15",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 207, DateTimeKind.Unspecified).AddTicks(4716),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "68516331",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 17,
                            Addresses = "Some Adress 16",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 521, DateTimeKind.Unspecified).AddTicks(3071),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "74086869",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 18,
                            Addresses = "Some Adress 17",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 335, DateTimeKind.Unspecified).AddTicks(3260),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "41980421",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 19,
                            Addresses = "Some Adress 18",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 166, DateTimeKind.Unspecified).AddTicks(5456),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "14405129",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 20,
                            Addresses = "Some Adress 19",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 510, DateTimeKind.Unspecified).AddTicks(2179),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "14229094",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 21,
                            Addresses = "Some Adress 20",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 636, DateTimeKind.Unspecified).AddTicks(5801),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "30080898",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 22,
                            Addresses = "Some Adress 21",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 489, DateTimeKind.Unspecified).AddTicks(7269),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "91630062",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 23,
                            Addresses = "Some Adress 22",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 608, DateTimeKind.Unspecified).AddTicks(8930),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "21276578",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 24,
                            Addresses = "Some Adress 23",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 711, DateTimeKind.Unspecified).AddTicks(8604),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "71106215",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 25,
                            Addresses = "Some Adress 24",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 600, DateTimeKind.Unspecified).AddTicks(3090),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "78707150",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 26,
                            Addresses = "Some Adress 25",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 726, DateTimeKind.Unspecified).AddTicks(9274),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "89033297",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 27,
                            Addresses = "Some Adress 26",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 447, DateTimeKind.Unspecified).AddTicks(447),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "59826613",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 28,
                            Addresses = "Some Adress 27",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 823, DateTimeKind.Unspecified).AddTicks(9111),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "84674432",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 29,
                            Addresses = "Some Adress 28",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 986, DateTimeKind.Unspecified).AddTicks(6587),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "29653971",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 30,
                            Addresses = "Some Adress 29",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 619, DateTimeKind.Unspecified).AddTicks(3055),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "68010938",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 31,
                            Addresses = "Some Adress 30",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 371, DateTimeKind.Unspecified).AddTicks(6032),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "58549335",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 32,
                            Addresses = "Some Adress 31",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 695, DateTimeKind.Unspecified).AddTicks(3379),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "10219598",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 33,
                            Addresses = "Some Adress 32",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 636, DateTimeKind.Unspecified).AddTicks(698),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "99884480",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 34,
                            Addresses = "Some Adress 33",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 356, DateTimeKind.Unspecified).AddTicks(5161),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "17844253",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 35,
                            Addresses = "Some Adress 34",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 765, DateTimeKind.Unspecified).AddTicks(9094),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "81747270",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 36,
                            Addresses = "Some Adress 35",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 948, DateTimeKind.Unspecified).AddTicks(8332),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "93047067",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 37,
                            Addresses = "Some Adress 36",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 296, DateTimeKind.Unspecified).AddTicks(6739),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "47174406",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 38,
                            Addresses = "Some Adress 37",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 289, DateTimeKind.Unspecified).AddTicks(5732),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "60131879",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 39,
                            Addresses = "Some Adress 38",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 698, DateTimeKind.Unspecified).AddTicks(6008),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "28076827",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 40,
                            Addresses = "Some Adress 39",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 477, DateTimeKind.Unspecified).AddTicks(3647),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "41233923",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 41,
                            Addresses = "Some Adress 40",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 953, DateTimeKind.Unspecified).AddTicks(6966),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "61198392",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 42,
                            Addresses = "Some Adress 41",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 611, DateTimeKind.Unspecified).AddTicks(875),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "29294536",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 43,
                            Addresses = "Some Adress 42",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 609, DateTimeKind.Unspecified).AddTicks(3925),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "77524176",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 44,
                            Addresses = "Some Adress 43",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 960, DateTimeKind.Unspecified).AddTicks(3069),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "29700983",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 45,
                            Addresses = "Some Adress 44",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 478, DateTimeKind.Unspecified).AddTicks(3056),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "75081944",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 46,
                            Addresses = "Some Adress 45",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 953, DateTimeKind.Unspecified).AddTicks(2828),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "22924874",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 47,
                            Addresses = "Some Adress 46",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 702, DateTimeKind.Unspecified).AddTicks(2881),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "41545708",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 48,
                            Addresses = "Some Adress 47",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 623, DateTimeKind.Unspecified).AddTicks(582),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "54571307",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 49,
                            Addresses = "Some Adress 48",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 264, DateTimeKind.Unspecified).AddTicks(4256),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "37495365",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 50,
                            Addresses = "Some Adress 49",
                            DateofBirth = new DateTime(1, 1, 1, 0, 0, 0, 127, DateTimeKind.Unspecified).AddTicks(7457),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "38212128",
                            SecondName = "Fernandez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
