// <auto-generated />
using System;
using BankTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankTest.Migrations
{
    [DbContext(typeof(BankTestContext))]
    [Migration("20220604081151_ww1")]
    partial class ww1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankTest.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PersonalPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Addresses = "Some Adress 0",
                            DateofBirth = new DateTime(2008, 6, 4, 10, 11, 50, 571, DateTimeKind.Local).AddTicks(9408),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "45076636",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 2,
                            Addresses = "Some Adress 1",
                            DateofBirth = new DateTime(1951, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(1427),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "79612147",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 3,
                            Addresses = "Some Adress 2",
                            DateofBirth = new DateTime(1997, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(1937),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "55477666",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 4,
                            Addresses = "Some Adress 3",
                            DateofBirth = new DateTime(2011, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2056),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "15834745",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 5,
                            Addresses = "Some Adress 4",
                            DateofBirth = new DateTime(1980, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2084),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "40010584",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 6,
                            Addresses = "Some Adress 5",
                            DateofBirth = new DateTime(1962, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2111),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "78798133",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 7,
                            Addresses = "Some Adress 6",
                            DateofBirth = new DateTime(1991, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2130),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "62331062",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 8,
                            Addresses = "Some Adress 7",
                            DateofBirth = new DateTime(2007, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2148),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "84798685",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 9,
                            Addresses = "Some Adress 8",
                            DateofBirth = new DateTime(1951, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2168),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "46105097",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 10,
                            Addresses = "Some Adress 9",
                            DateofBirth = new DateTime(1946, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2187),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "62111441",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 11,
                            Addresses = "Some Adress 10",
                            DateofBirth = new DateTime(1986, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2205),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "19378248",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 12,
                            Addresses = "Some Adress 11",
                            DateofBirth = new DateTime(1962, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2225),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "29195358",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 13,
                            Addresses = "Some Adress 12",
                            DateofBirth = new DateTime(2004, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2243),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "22936505",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 14,
                            Addresses = "Some Adress 13",
                            DateofBirth = new DateTime(1968, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2261),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "62595291",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 15,
                            Addresses = "Some Adress 14",
                            DateofBirth = new DateTime(1999, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2279),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "21296601",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 16,
                            Addresses = "Some Adress 15",
                            DateofBirth = new DateTime(2008, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2297),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "37352767",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 17,
                            Addresses = "Some Adress 16",
                            DateofBirth = new DateTime(2003, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2315),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "67139214",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 18,
                            Addresses = "Some Adress 17",
                            DateofBirth = new DateTime(1999, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2334),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "11717788",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 19,
                            Addresses = "Some Adress 18",
                            DateofBirth = new DateTime(1952, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2352),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "82709174",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 20,
                            Addresses = "Some Adress 19",
                            DateofBirth = new DateTime(1961, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2418),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "54677637",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 21,
                            Addresses = "Some Adress 20",
                            DateofBirth = new DateTime(1987, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2437),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "43844514",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 22,
                            Addresses = "Some Adress 21",
                            DateofBirth = new DateTime(1995, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2454),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "35489966",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 23,
                            Addresses = "Some Adress 22",
                            DateofBirth = new DateTime(1983, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2473),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "69921246",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 24,
                            Addresses = "Some Adress 23",
                            DateofBirth = new DateTime(1979, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2490),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "54549260",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 25,
                            Addresses = "Some Adress 24",
                            DateofBirth = new DateTime(1969, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2508),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "91620321",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 26,
                            Addresses = "Some Adress 25",
                            DateofBirth = new DateTime(1986, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2526),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "59314587",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 27,
                            Addresses = "Some Adress 26",
                            DateofBirth = new DateTime(1973, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2544),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "50308365",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 28,
                            Addresses = "Some Adress 27",
                            DateofBirth = new DateTime(1959, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2562),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "45802447",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 29,
                            Addresses = "Some Adress 28",
                            DateofBirth = new DateTime(1948, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2580),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "99590447",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 30,
                            Addresses = "Some Adress 29",
                            DateofBirth = new DateTime(1999, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2598),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "89363163",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 31,
                            Addresses = "Some Adress 30",
                            DateofBirth = new DateTime(1996, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2616),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "54349663",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 32,
                            Addresses = "Some Adress 31",
                            DateofBirth = new DateTime(1980, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2635),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "75248157",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 33,
                            Addresses = "Some Adress 32",
                            DateofBirth = new DateTime(1963, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2653),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "63167578",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 34,
                            Addresses = "Some Adress 33",
                            DateofBirth = new DateTime(1944, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2716),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "22022861",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 35,
                            Addresses = "Some Adress 34",
                            DateofBirth = new DateTime(2006, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2738),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "78102767",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 36,
                            Addresses = "Some Adress 35",
                            DateofBirth = new DateTime(1969, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2755),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "83577659",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 37,
                            Addresses = "Some Adress 36",
                            DateofBirth = new DateTime(1977, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2773),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "38040136",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 38,
                            Addresses = "Some Adress 37",
                            DateofBirth = new DateTime(2007, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2791),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "17465817",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 39,
                            Addresses = "Some Adress 38",
                            DateofBirth = new DateTime(2010, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2808),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "72053398",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 40,
                            Addresses = "Some Adress 39",
                            DateofBirth = new DateTime(1990, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2826),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "26214067",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 41,
                            Addresses = "Some Adress 40",
                            DateofBirth = new DateTime(2008, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2844),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "71078762",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 42,
                            Addresses = "Some Adress 41",
                            DateofBirth = new DateTime(1979, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2862),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "80008898",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 43,
                            Addresses = "Some Adress 42",
                            DateofBirth = new DateTime(1967, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2879),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "58591074",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 44,
                            Addresses = "Some Adress 43",
                            DateofBirth = new DateTime(1985, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2897),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "71277502",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 45,
                            Addresses = "Some Adress 44",
                            DateofBirth = new DateTime(1950, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2914),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "28126532",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 46,
                            Addresses = "Some Adress 45",
                            DateofBirth = new DateTime(1985, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2932),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "74530399",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 47,
                            Addresses = "Some Adress 46",
                            DateofBirth = new DateTime(1981, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2950),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "45784177",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 48,
                            Addresses = "Some Adress 47",
                            DateofBirth = new DateTime(1955, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2967),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "78681836",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 49,
                            Addresses = "Some Adress 48",
                            DateofBirth = new DateTime(1992, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(2985),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "80211998",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 50,
                            Addresses = "Some Adress 49",
                            DateofBirth = new DateTime(1978, 6, 4, 10, 11, 50, 577, DateTimeKind.Local).AddTicks(3095),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "61181391",
                            SecondName = "Garcia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
