// <auto-generated />
using System;
using BankTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankTest.Migrations
{
    [DbContext(typeof(BankTestContext))]
    [Migration("20220603142648_format-date")]
    partial class formatdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankTest.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Addresses = "Some Adress 0",
                            DateofBirth = new DateTime(2000, 6, 3, 16, 26, 48, 91, DateTimeKind.Local).AddTicks(928),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "17336685",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 2,
                            Addresses = "Some Adress 1",
                            DateofBirth = new DateTime(1947, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(2629),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "17608081",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 3,
                            Addresses = "Some Adress 2",
                            DateofBirth = new DateTime(1966, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3223),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "72111981",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 4,
                            Addresses = "Some Adress 3",
                            DateofBirth = new DateTime(1943, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3258),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "95376215",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 5,
                            Addresses = "Some Adress 4",
                            DateofBirth = new DateTime(1956, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3278),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "71479389",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 6,
                            Addresses = "Some Adress 5",
                            DateofBirth = new DateTime(1944, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3306),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "92999690",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 7,
                            Addresses = "Some Adress 6",
                            DateofBirth = new DateTime(1958, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3324),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "12593125",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 8,
                            Addresses = "Some Adress 7",
                            DateofBirth = new DateTime(1953, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3342),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "78629653",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 9,
                            Addresses = "Some Adress 8",
                            DateofBirth = new DateTime(2009, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3359),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "26101281",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 10,
                            Addresses = "Some Adress 9",
                            DateofBirth = new DateTime(1965, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3378),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "18356030",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 11,
                            Addresses = "Some Adress 10",
                            DateofBirth = new DateTime(2009, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3396),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "21674340",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 12,
                            Addresses = "Some Adress 11",
                            DateofBirth = new DateTime(1959, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3415),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "76894160",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 13,
                            Addresses = "Some Adress 12",
                            DateofBirth = new DateTime(1945, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3432),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "52973362",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 14,
                            Addresses = "Some Adress 13",
                            DateofBirth = new DateTime(1999, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3450),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "14032700",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 15,
                            Addresses = "Some Adress 14",
                            DateofBirth = new DateTime(1951, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3467),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "37928152",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 16,
                            Addresses = "Some Adress 15",
                            DateofBirth = new DateTime(1975, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3484),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "12418982",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 17,
                            Addresses = "Some Adress 16",
                            DateofBirth = new DateTime(2010, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3581),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "13076999",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 18,
                            Addresses = "Some Adress 17",
                            DateofBirth = new DateTime(1975, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3607),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "73114875",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 19,
                            Addresses = "Some Adress 18",
                            DateofBirth = new DateTime(1961, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3626),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "54472254",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 20,
                            Addresses = "Some Adress 19",
                            DateofBirth = new DateTime(1944, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3644),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "61360709",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 21,
                            Addresses = "Some Adress 20",
                            DateofBirth = new DateTime(1960, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3662),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "33446566",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 22,
                            Addresses = "Some Adress 21",
                            DateofBirth = new DateTime(1986, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3679),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "88742417",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 23,
                            Addresses = "Some Adress 22",
                            DateofBirth = new DateTime(1961, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3697),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "23701436",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 24,
                            Addresses = "Some Adress 23",
                            DateofBirth = new DateTime(1962, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3714),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "13963127",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 25,
                            Addresses = "Some Adress 24",
                            DateofBirth = new DateTime(1988, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3731),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "14419730",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 26,
                            Addresses = "Some Adress 25",
                            DateofBirth = new DateTime(1962, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3748),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "51947746",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 27,
                            Addresses = "Some Adress 26",
                            DateofBirth = new DateTime(1972, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3766),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "70720639",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 28,
                            Addresses = "Some Adress 27",
                            DateofBirth = new DateTime(2011, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3784),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "63292392",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 29,
                            Addresses = "Some Adress 28",
                            DateofBirth = new DateTime(2003, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3801),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "40510048",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 30,
                            Addresses = "Some Adress 29",
                            DateofBirth = new DateTime(1987, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3818),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "47014560",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 31,
                            Addresses = "Some Adress 30",
                            DateofBirth = new DateTime(1946, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3835),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "10906145",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 32,
                            Addresses = "Some Adress 31",
                            DateofBirth = new DateTime(1961, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3903),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "56768416",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 33,
                            Addresses = "Some Adress 32",
                            DateofBirth = new DateTime(1989, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3927),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "99972968",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 34,
                            Addresses = "Some Adress 33",
                            DateofBirth = new DateTime(1944, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3946),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "51018563",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 35,
                            Addresses = "Some Adress 34",
                            DateofBirth = new DateTime(1977, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3966),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "45320851",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 36,
                            Addresses = "Some Adress 35",
                            DateofBirth = new DateTime(1954, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(3983),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "45253143",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 37,
                            Addresses = "Some Adress 36",
                            DateofBirth = new DateTime(1952, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4001),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "69382341",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 38,
                            Addresses = "Some Adress 37",
                            DateofBirth = new DateTime(1950, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4019),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "90098365",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 39,
                            Addresses = "Some Adress 38",
                            DateofBirth = new DateTime(1976, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4037),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "49141539",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 40,
                            Addresses = "Some Adress 39",
                            DateofBirth = new DateTime(1985, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4054),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "42929517",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 41,
                            Addresses = "Some Adress 40",
                            DateofBirth = new DateTime(1965, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4072),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "41584422",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 42,
                            Addresses = "Some Adress 41",
                            DateofBirth = new DateTime(2006, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4089),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "42370239",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 43,
                            Addresses = "Some Adress 42",
                            DateofBirth = new DateTime(2010, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4107),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "87970470",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 44,
                            Addresses = "Some Adress 43",
                            DateofBirth = new DateTime(1969, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4124),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "84509445",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 45,
                            Addresses = "Some Adress 44",
                            DateofBirth = new DateTime(2010, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4142),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "94365155",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 46,
                            Addresses = "Some Adress 45",
                            DateofBirth = new DateTime(1993, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4159),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "64899280",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 47,
                            Addresses = "Some Adress 46",
                            DateofBirth = new DateTime(1988, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4231),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "60686877",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 48,
                            Addresses = "Some Adress 47",
                            DateofBirth = new DateTime(1965, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4252),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "63267722",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 49,
                            Addresses = "Some Adress 48",
                            DateofBirth = new DateTime(1953, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4269),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "74636464",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 50,
                            Addresses = "Some Adress 49",
                            DateofBirth = new DateTime(2011, 6, 3, 16, 26, 48, 96, DateTimeKind.Local).AddTicks(4287),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "95731405",
                            SecondName = "Garcia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
