// <auto-generated />
using System;
using BankTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankTest.Migrations
{
    [DbContext(typeof(BankTestContext))]
    [Migration("20220620062621_addeed EntityBase1")]
    partial class addeedEntityBase1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankTest.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PersonalPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Addresses = "Some Adress 0",
                            DateofBirth = new DateTime(1944, 6, 20, 8, 26, 20, 623, DateTimeKind.Local).AddTicks(8016),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "34147601",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 2,
                            Addresses = "Some Adress 1",
                            DateofBirth = new DateTime(1992, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4445),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "76755930",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 3,
                            Addresses = "Some Adress 2",
                            DateofBirth = new DateTime(1959, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4679),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "66349388",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 4,
                            Addresses = "Some Adress 3",
                            DateofBirth = new DateTime(1997, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4790),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "81725871",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 5,
                            Addresses = "Some Adress 4",
                            DateofBirth = new DateTime(1978, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4813),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "27857148",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 6,
                            Addresses = "Some Adress 5",
                            DateofBirth = new DateTime(1949, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4836),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "92687141",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 7,
                            Addresses = "Some Adress 6",
                            DateofBirth = new DateTime(1997, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4855),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "60573828",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 8,
                            Addresses = "Some Adress 7",
                            DateofBirth = new DateTime(1988, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4873),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "48252628",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 9,
                            Addresses = "Some Adress 8",
                            DateofBirth = new DateTime(1982, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4890),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "83834656",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 10,
                            Addresses = "Some Adress 9",
                            DateofBirth = new DateTime(1977, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4908),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "72393690",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 11,
                            Addresses = "Some Adress 10",
                            DateofBirth = new DateTime(2011, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4927),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "89461406",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 12,
                            Addresses = "Some Adress 11",
                            DateofBirth = new DateTime(1958, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4944),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "87180521",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 13,
                            Addresses = "Some Adress 12",
                            DateofBirth = new DateTime(1987, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4962),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "52886480",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 14,
                            Addresses = "Some Adress 13",
                            DateofBirth = new DateTime(1998, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4979),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "55129092",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 15,
                            Addresses = "Some Adress 14",
                            DateofBirth = new DateTime(1956, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(4995),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "51511129",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 16,
                            Addresses = "Some Adress 15",
                            DateofBirth = new DateTime(1966, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5013),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "86224335",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 17,
                            Addresses = "Some Adress 16",
                            DateofBirth = new DateTime(1997, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5030),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "22779415",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 18,
                            Addresses = "Some Adress 17",
                            DateofBirth = new DateTime(1988, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5048),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "32835427",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 19,
                            Addresses = "Some Adress 18",
                            DateofBirth = new DateTime(1978, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5116),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "68135772",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 20,
                            Addresses = "Some Adress 19",
                            DateofBirth = new DateTime(1945, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5134),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "37882916",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 21,
                            Addresses = "Some Adress 20",
                            DateofBirth = new DateTime(2012, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5151),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "91619549",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 22,
                            Addresses = "Some Adress 21",
                            DateofBirth = new DateTime(1973, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5168),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "21164389",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 23,
                            Addresses = "Some Adress 22",
                            DateofBirth = new DateTime(1947, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5185),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "92656963",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 24,
                            Addresses = "Some Adress 23",
                            DateofBirth = new DateTime(1997, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5202),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "92436521",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 25,
                            Addresses = "Some Adress 24",
                            DateofBirth = new DateTime(1946, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5219),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "24528717",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 26,
                            Addresses = "Some Adress 25",
                            DateofBirth = new DateTime(2002, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5235),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "68111636",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 27,
                            Addresses = "Some Adress 26",
                            DateofBirth = new DateTime(1987, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5253),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "11810636",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 28,
                            Addresses = "Some Adress 27",
                            DateofBirth = new DateTime(1991, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5270),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "46759947",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 29,
                            Addresses = "Some Adress 28",
                            DateofBirth = new DateTime(1997, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5287),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "70169558",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 30,
                            Addresses = "Some Adress 29",
                            DateofBirth = new DateTime(1972, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5304),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "91315957",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 31,
                            Addresses = "Some Adress 30",
                            DateofBirth = new DateTime(2009, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5321),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "18987690",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 32,
                            Addresses = "Some Adress 31",
                            DateofBirth = new DateTime(1954, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5337),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "97679828",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 33,
                            Addresses = "Some Adress 32",
                            DateofBirth = new DateTime(1949, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5354),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "71716163",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 34,
                            Addresses = "Some Adress 33",
                            DateofBirth = new DateTime(1949, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5418),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "41574101",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 35,
                            Addresses = "Some Adress 34",
                            DateofBirth = new DateTime(1955, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5438),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "84371109",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 36,
                            Addresses = "Some Adress 35",
                            DateofBirth = new DateTime(1993, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5486),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "96196029",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 37,
                            Addresses = "Some Adress 36",
                            DateofBirth = new DateTime(1995, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5504),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "46270468",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 38,
                            Addresses = "Some Adress 37",
                            DateofBirth = new DateTime(1994, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5521),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "19445758",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 39,
                            Addresses = "Some Adress 38",
                            DateofBirth = new DateTime(1989, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5538),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "69832619",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 40,
                            Addresses = "Some Adress 39",
                            DateofBirth = new DateTime(1975, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5555),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "69969116",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 41,
                            Addresses = "Some Adress 40",
                            DateofBirth = new DateTime(1997, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5572),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "61534048",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 42,
                            Addresses = "Some Adress 41",
                            DateofBirth = new DateTime(1997, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5588),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "11893970",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 43,
                            Addresses = "Some Adress 42",
                            DateofBirth = new DateTime(1951, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5605),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "59237584",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 44,
                            Addresses = "Some Adress 43",
                            DateofBirth = new DateTime(1977, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5622),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "86610184",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 45,
                            Addresses = "Some Adress 44",
                            DateofBirth = new DateTime(1956, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5639),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "46021665",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 46,
                            Addresses = "Some Adress 45",
                            DateofBirth = new DateTime(2002, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5656),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "52357205",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 47,
                            Addresses = "Some Adress 46",
                            DateofBirth = new DateTime(1969, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5673),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "28717188",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 48,
                            Addresses = "Some Adress 47",
                            DateofBirth = new DateTime(1965, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5689),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "80938918",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 49,
                            Addresses = "Some Adress 48",
                            DateofBirth = new DateTime(1996, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5752),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "14175314",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 50,
                            Addresses = "Some Adress 49",
                            DateofBirth = new DateTime(1957, 6, 20, 8, 26, 20, 628, DateTimeKind.Local).AddTicks(5771),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "81199315",
                            SecondName = "Hernandez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
