// <auto-generated />
using System;
using BankTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankTest.Migrations
{
    [DbContext(typeof(BankTestContext))]
    [Migration("20220603143812_newM")]
    partial class newM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankTest.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Addresses = "Some Adress 0",
                            DateofBirth = new DateTime(1960, 6, 3, 16, 38, 12, 308, DateTimeKind.Local).AddTicks(1239),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "96301868",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 2,
                            Addresses = "Some Adress 1",
                            DateofBirth = new DateTime(1961, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9313),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "16623313",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 3,
                            Addresses = "Some Adress 2",
                            DateofBirth = new DateTime(1990, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9611),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "53726758",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 4,
                            Addresses = "Some Adress 3",
                            DateofBirth = new DateTime(1961, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9645),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "32902512",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 5,
                            Addresses = "Some Adress 4",
                            DateofBirth = new DateTime(1950, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9664),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "15968170",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 6,
                            Addresses = "Some Adress 5",
                            DateofBirth = new DateTime(1949, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9687),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "29709408",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 7,
                            Addresses = "Some Adress 6",
                            DateofBirth = new DateTime(1993, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9705),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "96684897",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 8,
                            Addresses = "Some Adress 7",
                            DateofBirth = new DateTime(1992, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9723),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "63613693",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 9,
                            Addresses = "Some Adress 8",
                            DateofBirth = new DateTime(2009, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9741),
                            FirstName = "Jhon",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "69619803",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 10,
                            Addresses = "Some Adress 9",
                            DateofBirth = new DateTime(2006, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9760),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "18076775",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 11,
                            Addresses = "Some Adress 10",
                            DateofBirth = new DateTime(1989, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9779),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "58322755",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 12,
                            Addresses = "Some Adress 11",
                            DateofBirth = new DateTime(1990, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9796),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "82896649",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 13,
                            Addresses = "Some Adress 12",
                            DateofBirth = new DateTime(1975, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9814),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "49887687",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 14,
                            Addresses = "Some Adress 13",
                            DateofBirth = new DateTime(1985, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9830),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "50843100",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 15,
                            Addresses = "Some Adress 14",
                            DateofBirth = new DateTime(1943, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9847),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "81659176",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 16,
                            Addresses = "Some Adress 15",
                            DateofBirth = new DateTime(2008, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9926),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "40002217",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 17,
                            Addresses = "Some Adress 16",
                            DateofBirth = new DateTime(1983, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9946),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "41066179",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 18,
                            Addresses = "Some Adress 17",
                            DateofBirth = new DateTime(2006, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9966),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "83436226",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 19,
                            Addresses = "Some Adress 18",
                            DateofBirth = new DateTime(1950, 6, 3, 16, 38, 12, 312, DateTimeKind.Local).AddTicks(9983),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "97595181",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 20,
                            Addresses = "Some Adress 19",
                            DateofBirth = new DateTime(1964, 6, 3, 16, 38, 12, 313, DateTimeKind.Local),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "21348760",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 21,
                            Addresses = "Some Adress 20",
                            DateofBirth = new DateTime(2012, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(17),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "64029925",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 22,
                            Addresses = "Some Adress 21",
                            DateofBirth = new DateTime(2009, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(34),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "70674821",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 23,
                            Addresses = "Some Adress 22",
                            DateofBirth = new DateTime(1989, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(51),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "66832341",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 24,
                            Addresses = "Some Adress 23",
                            DateofBirth = new DateTime(1947, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(67),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "46667863",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 25,
                            Addresses = "Some Adress 24",
                            DateofBirth = new DateTime(1957, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(84),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "82453603",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 26,
                            Addresses = "Some Adress 25",
                            DateofBirth = new DateTime(2010, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(100),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "90029060",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 27,
                            Addresses = "Some Adress 26",
                            DateofBirth = new DateTime(2000, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(117),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "77419027",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 28,
                            Addresses = "Some Adress 27",
                            DateofBirth = new DateTime(1993, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(134),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "94871139",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 29,
                            Addresses = "Some Adress 28",
                            DateofBirth = new DateTime(1977, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(151),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "71262773",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 30,
                            Addresses = "Some Adress 29",
                            DateofBirth = new DateTime(1985, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(167),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "89642932",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 31,
                            Addresses = "Some Adress 30",
                            DateofBirth = new DateTime(1972, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(227),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "26662903",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 32,
                            Addresses = "Some Adress 31",
                            DateofBirth = new DateTime(1955, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(247),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "96996608",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 33,
                            Addresses = "Some Adress 32",
                            DateofBirth = new DateTime(1996, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(265),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "25077048",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 34,
                            Addresses = "Some Adress 33",
                            DateofBirth = new DateTime(1964, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(283),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "38066675",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 35,
                            Addresses = "Some Adress 34",
                            DateofBirth = new DateTime(1993, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(301),
                            FirstName = "Carlos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "30454528",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 36,
                            Addresses = "Some Adress 35",
                            DateofBirth = new DateTime(2001, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(317),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "40414626",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 37,
                            Addresses = "Some Adress 36",
                            DateofBirth = new DateTime(1957, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(335),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "22271670",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 38,
                            Addresses = "Some Adress 37",
                            DateofBirth = new DateTime(1968, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(352),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "35528687",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 39,
                            Addresses = "Some Adress 38",
                            DateofBirth = new DateTime(2004, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(368),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "71644377",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 40,
                            Addresses = "Some Adress 39",
                            DateofBirth = new DateTime(2001, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(385),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "86443030",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 41,
                            Addresses = "Some Adress 40",
                            DateofBirth = new DateTime(1950, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(401),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "12703952",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 42,
                            Addresses = "Some Adress 41",
                            DateofBirth = new DateTime(1987, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(419),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "96224330",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 43,
                            Addresses = "Some Adress 42",
                            DateofBirth = new DateTime(1996, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(436),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "69484435",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 44,
                            Addresses = "Some Adress 43",
                            DateofBirth = new DateTime(1998, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(452),
                            FirstName = "Brayan",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "44353980",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 45,
                            Addresses = "Some Adress 44",
                            DateofBirth = new DateTime(1951, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(469),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "39877372",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 46,
                            Addresses = "Some Adress 45",
                            DateofBirth = new DateTime(2000, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(564),
                            FirstName = "Miguel",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "64357897",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 47,
                            Addresses = "Some Adress 46",
                            DateofBirth = new DateTime(1974, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(586),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "70202061",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 48,
                            Addresses = "Some Adress 47",
                            DateofBirth = new DateTime(1948, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(603),
                            FirstName = "Marcos",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "63285182",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 49,
                            Addresses = "Some Adress 48",
                            DateofBirth = new DateTime(1990, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(619),
                            FirstName = "Juliet",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "51971768",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 50,
                            Addresses = "Some Adress 49",
                            DateofBirth = new DateTime(2003, 6, 3, 16, 38, 12, 313, DateTimeKind.Local).AddTicks(636),
                            FirstName = "Tedd",
                            PersonalPhoto = "avatar.png",
                            PhoneNumber = "27735707",
                            SecondName = "Doe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
