// <auto-generated />
using System;
using BankTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankTest.Migrations
{
    [DbContext(typeof(BankTestContext))]
    [Migration("20220604080642_ww")]
    partial class ww
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankTest.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PersonalPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Addresses = "Some Adress 0",
                            DateofBirth = new DateTime(1996, 6, 4, 10, 6, 42, 10, DateTimeKind.Local).AddTicks(327),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "87143302",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 2,
                            Addresses = "Some Adress 1",
                            DateofBirth = new DateTime(1949, 6, 4, 10, 6, 42, 15, DateTimeKind.Local).AddTicks(9754),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "79188471",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 3,
                            Addresses = "Some Adress 2",
                            DateofBirth = new DateTime(1969, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(250),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "88359194",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 4,
                            Addresses = "Some Adress 3",
                            DateofBirth = new DateTime(1965, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(288),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "24751258",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 5,
                            Addresses = "Some Adress 4",
                            DateofBirth = new DateTime(1955, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(306),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "26409847",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 6,
                            Addresses = "Some Adress 5",
                            DateofBirth = new DateTime(1960, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(331),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "45550980",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 7,
                            Addresses = "Some Adress 6",
                            DateofBirth = new DateTime(1966, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(350),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "70401777",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 8,
                            Addresses = "Some Adress 7",
                            DateofBirth = new DateTime(2009, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(366),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "11470498",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 9,
                            Addresses = "Some Adress 8",
                            DateofBirth = new DateTime(1982, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(383),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "87617331",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 10,
                            Addresses = "Some Adress 9",
                            DateofBirth = new DateTime(1954, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(401),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "41614580",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 11,
                            Addresses = "Some Adress 10",
                            DateofBirth = new DateTime(1983, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(419),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "18577497",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 12,
                            Addresses = "Some Adress 11",
                            DateofBirth = new DateTime(2009, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(437),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "74815191",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 13,
                            Addresses = "Some Adress 12",
                            DateofBirth = new DateTime(1976, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(453),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "77797650",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 14,
                            Addresses = "Some Adress 13",
                            DateofBirth = new DateTime(1946, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(553),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "28558140",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 15,
                            Addresses = "Some Adress 14",
                            DateofBirth = new DateTime(1966, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(571),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "83362408",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 16,
                            Addresses = "Some Adress 15",
                            DateofBirth = new DateTime(1946, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(589),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "69334976",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 17,
                            Addresses = "Some Adress 16",
                            DateofBirth = new DateTime(1984, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(605),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "61252753",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 18,
                            Addresses = "Some Adress 17",
                            DateofBirth = new DateTime(1973, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(624),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "81655807",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 19,
                            Addresses = "Some Adress 18",
                            DateofBirth = new DateTime(1989, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(640),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "41652387",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 20,
                            Addresses = "Some Adress 19",
                            DateofBirth = new DateTime(1965, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(657),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "92253772",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 21,
                            Addresses = "Some Adress 20",
                            DateofBirth = new DateTime(1969, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(673),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "19960049",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 22,
                            Addresses = "Some Adress 21",
                            DateofBirth = new DateTime(1970, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(689),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "12553848",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 23,
                            Addresses = "Some Adress 22",
                            DateofBirth = new DateTime(1985, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1054),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "48140896",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 24,
                            Addresses = "Some Adress 23",
                            DateofBirth = new DateTime(1946, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1089),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "90083308",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 25,
                            Addresses = "Some Adress 24",
                            DateofBirth = new DateTime(2001, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1109),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "53318801",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 26,
                            Addresses = "Some Adress 25",
                            DateofBirth = new DateTime(1991, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1127),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "15832276",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 27,
                            Addresses = "Some Adress 26",
                            DateofBirth = new DateTime(2010, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1293),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "56874871",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 28,
                            Addresses = "Some Adress 27",
                            DateofBirth = new DateTime(1992, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1369),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "68442413",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 29,
                            Addresses = "Some Adress 28",
                            DateofBirth = new DateTime(1975, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1463),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "24393596",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 30,
                            Addresses = "Some Adress 29",
                            DateofBirth = new DateTime(1949, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1483),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "19277079",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 31,
                            Addresses = "Some Adress 30",
                            DateofBirth = new DateTime(1957, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1500),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "24509832",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 32,
                            Addresses = "Some Adress 31",
                            DateofBirth = new DateTime(2003, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1517),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "79840141",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 33,
                            Addresses = "Some Adress 32",
                            DateofBirth = new DateTime(1975, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1534),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "25168177",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 34,
                            Addresses = "Some Adress 33",
                            DateofBirth = new DateTime(1952, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1557),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "16601644",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 35,
                            Addresses = "Some Adress 34",
                            DateofBirth = new DateTime(1992, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1574),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "86679889",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 36,
                            Addresses = "Some Adress 35",
                            DateofBirth = new DateTime(2012, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1592),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "72810390",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 37,
                            Addresses = "Some Adress 36",
                            DateofBirth = new DateTime(1998, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1609),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "68477010",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 38,
                            Addresses = "Some Adress 37",
                            DateofBirth = new DateTime(1951, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1627),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "81489983",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 39,
                            Addresses = "Some Adress 38",
                            DateofBirth = new DateTime(1976, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1644),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "75720262",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 40,
                            Addresses = "Some Adress 39",
                            DateofBirth = new DateTime(1987, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1661),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "79275327",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 41,
                            Addresses = "Some Adress 40",
                            DateofBirth = new DateTime(1954, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1678),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "80034629",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 42,
                            Addresses = "Some Adress 41",
                            DateofBirth = new DateTime(1947, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1694),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "15029072",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 43,
                            Addresses = "Some Adress 42",
                            DateofBirth = new DateTime(1981, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1711),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "23546348",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 44,
                            Addresses = "Some Adress 43",
                            DateofBirth = new DateTime(1950, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1784),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "90146076",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 45,
                            Addresses = "Some Adress 44",
                            DateofBirth = new DateTime(2007, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1801),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "40578170",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 46,
                            Addresses = "Some Adress 45",
                            DateofBirth = new DateTime(1973, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1818),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "67878819",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 47,
                            Addresses = "Some Adress 46",
                            DateofBirth = new DateTime(1996, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1919),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "58668333",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 48,
                            Addresses = "Some Adress 47",
                            DateofBirth = new DateTime(1983, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1943),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "93664692",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 49,
                            Addresses = "Some Adress 48",
                            DateofBirth = new DateTime(1955, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1961),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "20039311",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 50,
                            Addresses = "Some Adress 49",
                            DateofBirth = new DateTime(1987, 6, 4, 10, 6, 42, 16, DateTimeKind.Local).AddTicks(1977),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "36601094",
                            SecondName = "Doe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
