// <auto-generated />
using System;
using BankTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankTest.Migrations
{
    [DbContext(typeof(BankTestContext))]
    partial class BankTestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankTest.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PersonalPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Addresses = "Some Adress 0",
                            DateofBirth = new DateTime(1973, 6, 23, 8, 29, 26, 268, DateTimeKind.Local).AddTicks(8489),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "34510230",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 2,
                            Addresses = "Some Adress 1",
                            DateofBirth = new DateTime(2002, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(1828),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "70590154",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 3,
                            Addresses = "Some Adress 2",
                            DateofBirth = new DateTime(1946, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(2515),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "73435580",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 4,
                            Addresses = "Some Adress 3",
                            DateofBirth = new DateTime(1981, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(2558),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "44399303",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 5,
                            Addresses = "Some Adress 4",
                            DateofBirth = new DateTime(1987, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(2739),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "87679068",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 6,
                            Addresses = "Some Adress 5",
                            DateofBirth = new DateTime(1953, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(2765),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "93184862",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 7,
                            Addresses = "Some Adress 6",
                            DateofBirth = new DateTime(2003, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(2785),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "67544689",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 8,
                            Addresses = "Some Adress 7",
                            DateofBirth = new DateTime(1973, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(2804),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "58953112",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 9,
                            Addresses = "Some Adress 8",
                            DateofBirth = new DateTime(1943, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(2823),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "27762003",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 10,
                            Addresses = "Some Adress 9",
                            DateofBirth = new DateTime(1945, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(2843),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "60371422",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 11,
                            Addresses = "Some Adress 10",
                            DateofBirth = new DateTime(1997, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(2987),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "23636350",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 12,
                            Addresses = "Some Adress 11",
                            DateofBirth = new DateTime(1963, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3009),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "35436497",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 13,
                            Addresses = "Some Adress 12",
                            DateofBirth = new DateTime(1997, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3190),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "31159873",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 14,
                            Addresses = "Some Adress 13",
                            DateofBirth = new DateTime(1991, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3208),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "36811850",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 15,
                            Addresses = "Some Adress 14",
                            DateofBirth = new DateTime(1949, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3227),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "23727374",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 16,
                            Addresses = "Some Adress 15",
                            DateofBirth = new DateTime(2001, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3244),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "82906708",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 17,
                            Addresses = "Some Adress 16",
                            DateofBirth = new DateTime(1992, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3262),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "71018340",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 18,
                            Addresses = "Some Adress 17",
                            DateofBirth = new DateTime(1944, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3284),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "48758256",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 19,
                            Addresses = "Some Adress 18",
                            DateofBirth = new DateTime(1993, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3303),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "44674159",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 20,
                            Addresses = "Some Adress 19",
                            DateofBirth = new DateTime(1960, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3321),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "35391558",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 21,
                            Addresses = "Some Adress 20",
                            DateofBirth = new DateTime(1966, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3339),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "39917969",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 22,
                            Addresses = "Some Adress 21",
                            DateofBirth = new DateTime(2007, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3357),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "79884981",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 23,
                            Addresses = "Some Adress 22",
                            DateofBirth = new DateTime(1950, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3375),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "73628360",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 24,
                            Addresses = "Some Adress 23",
                            DateofBirth = new DateTime(1974, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3393),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "12309255",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 25,
                            Addresses = "Some Adress 24",
                            DateofBirth = new DateTime(1951, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3411),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "90248121",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 26,
                            Addresses = "Some Adress 25",
                            DateofBirth = new DateTime(1976, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3481),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "85851043",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 27,
                            Addresses = "Some Adress 26",
                            DateofBirth = new DateTime(1951, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3504),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "30754663",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 28,
                            Addresses = "Some Adress 27",
                            DateofBirth = new DateTime(1946, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3522),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "43731259",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 29,
                            Addresses = "Some Adress 28",
                            DateofBirth = new DateTime(1998, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3544),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "17209292",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 30,
                            Addresses = "Some Adress 29",
                            DateofBirth = new DateTime(1972, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3562),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "86839203",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 31,
                            Addresses = "Some Adress 30",
                            DateofBirth = new DateTime(1962, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3580),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "46047277",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 32,
                            Addresses = "Some Adress 31",
                            DateofBirth = new DateTime(1958, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3598),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "57167407",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 33,
                            Addresses = "Some Adress 32",
                            DateofBirth = new DateTime(1996, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3617),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "83942255",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 34,
                            Addresses = "Some Adress 33",
                            DateofBirth = new DateTime(1966, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3636),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "42821420",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 35,
                            Addresses = "Some Adress 34",
                            DateofBirth = new DateTime(2000, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3655),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar4.png",
                            PhoneNumber = "18114039",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 36,
                            Addresses = "Some Adress 35",
                            DateofBirth = new DateTime(1957, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3673),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "71871473",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 37,
                            Addresses = "Some Adress 36",
                            DateofBirth = new DateTime(1965, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3691),
                            FirstName = "Juliet",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "87133033",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 38,
                            Addresses = "Some Adress 37",
                            DateofBirth = new DateTime(1979, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3709),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "62874577",
                            SecondName = "Fernandez"
                        },
                        new
                        {
                            ID = 39,
                            Addresses = "Some Adress 38",
                            DateofBirth = new DateTime(1982, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3726),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "60936002",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 40,
                            Addresses = "Some Adress 39",
                            DateofBirth = new DateTime(1985, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3744),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "79134967",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 41,
                            Addresses = "Some Adress 40",
                            DateofBirth = new DateTime(1998, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3819),
                            FirstName = "Tedd",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "80540903",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 42,
                            Addresses = "Some Adress 41",
                            DateofBirth = new DateTime(1968, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3839),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "64740452",
                            SecondName = "Doe"
                        },
                        new
                        {
                            ID = 43,
                            Addresses = "Some Adress 42",
                            DateofBirth = new DateTime(2006, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3857),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "26498309",
                            SecondName = "Garcia"
                        },
                        new
                        {
                            ID = 44,
                            Addresses = "Some Adress 43",
                            DateofBirth = new DateTime(1986, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3875),
                            FirstName = "Carlos",
                            PersonalPhoto = "img_avatar3.png",
                            PhoneNumber = "75429943",
                            SecondName = "Lee"
                        },
                        new
                        {
                            ID = 45,
                            Addresses = "Some Adress 44",
                            DateofBirth = new DateTime(2007, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3893),
                            FirstName = "Marcos",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "15345470",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 46,
                            Addresses = "Some Adress 45",
                            DateofBirth = new DateTime(1970, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3911),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar1.png",
                            PhoneNumber = "78290367",
                            SecondName = "Hernandez"
                        },
                        new
                        {
                            ID = 47,
                            Addresses = "Some Adress 46",
                            DateofBirth = new DateTime(2010, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3929),
                            FirstName = "Brayan",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "67549522",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 48,
                            Addresses = "Some Adress 47",
                            DateofBirth = new DateTime(1950, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3946),
                            FirstName = "Jhon",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "34115009",
                            SecondName = "Tapanez"
                        },
                        new
                        {
                            ID = 49,
                            Addresses = "Some Adress 48",
                            DateofBirth = new DateTime(1951, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3964),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar2.png",
                            PhoneNumber = "47381610",
                            SecondName = "Stampton"
                        },
                        new
                        {
                            ID = 50,
                            Addresses = "Some Adress 49",
                            DateofBirth = new DateTime(1995, 6, 23, 8, 29, 26, 276, DateTimeKind.Local).AddTicks(3982),
                            FirstName = "Miguel",
                            PersonalPhoto = "img_avatar5.png",
                            PhoneNumber = "72701298",
                            SecondName = "Doe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
